### ISSUE TITLE
Cannot bind argument to parameter 'Exception' because it is null.

### ISSUE THREAD

**Issue by nightroman** [anthonyg-1/PSGraphQL#12]
In a particular scenario, `Invoke-GraphQLQuery` fails internally with not useful error:

```
System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Exception' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\PSGraphQL\1.9.0\Functions\Invoke-GraphQLQuery.ps1:410 char:40
+ …            Write-Error -Exception $_.Exception.InnerException -Catego …
```

It's a little fiddly to give the exact reproducible case.
Here is some contrived example:

```powershell
Invoke-GraphQLQuery -Uri https://api.nexardev.com/foobar
```

This simple snippet demonstrates the module code problem (incorrect assumption that `$_.Exception` is not null):

```powershell
try {
    Invoke-RestMethod -Uri https://api.nexardev.com/foobar
}
catch {
    Write-Error -Exception $_.Exception.InnerException -Category InvalidOperation -ErrorAction Stop
}
```

It fails with the same not useful error.

Compare with this amended snippet:

```powershell
try {
    Invoke-RestMethod -Uri https://api.nexardev.com/foobar
}
catch {
    Write-Error -Exception $_.Exception -Category InvalidOperation -ErrorAction Stop
}
```

This amended snippet fails with the useful error:

```
Response status code does not indicate success: 404 (Not Found).
```

NB The problem is not about "funny URLs". In the original problem case I have the same issue with a valid URL and valid query, where the query fails (expectedly). `Invoke-GraphQLQuery` should emit that query failure error, not the current internal error.

**Comment by anthonyg-1** [comment]
Hi @nightroman, the way you've described the issue makes sense. There was a reason why I was throwing the inner exception with Write-Error prior as Invoke-RestMethod's outer exception wasn't particularly useful. I still want to prioritize the inner exception so I made the following code change to version 1.9.1. 

```powershell
try {
    $response = Invoke-RestMethod @params
}
catch {
    if ($null -ne $_.Exception.InnerException) {
        Write-Error -Exception $_.Exception.InnerException -Category InvalidOperation -ErrorAction Stop
    }
    else {
        Write-Error -Exception $_.Exception -Category InvalidOperation -ErrorAction Stop
    }
}
```

Please let me know if this does not suffice and I'll implement your recommendation if not. I'll keep the issue open until you acknowledge this code change remediates the issue.

**Comment by nightroman** [comment]
I think this is the totally reasonable fix of the current issue.

**Comment by anthonyg-1** [comment]
> I think this is the totally reasonable fix of the current issue.

Thanks @nightroman, I'll close the issue. Please feel free to re-open if this doesn't fully solve.
