### ISSUE TITLE
Keep receiving: Not a valid GraphQL query or mutation. Verify syntax and try again.

### ISSUE THREAD

**Issue by soke1556** [anthonyg-1/PSGraphQL#2]
I keep receiving the error described in the subject. What am I doing wrong? (Thanks for your library!)
```ps
$uri = "https://xxxx/graphql"
$accessKey = 'Bearer xxxxx' 

$myQuery = '
    query{ 
        pages {
        list{
            id
            isPublished
            isPrivate
            path
            locale
            createdAt
            updatedAt
        }
        }
    }
'

$requestHeaders = @{ "Authorization" = $accessKey }

$jsonResult = Invoke-GraphQLQuery -Query $myQuery -Headers $requestHeaders -Uri $uri

Write-Output $jsonResult
```

**Comment by anthonyg-1** [comment]
Ah I see what happened. I incorrectly parsed the incoming query. Fixing
that now. The version you'll want that should address this is 1.0.3. Please
let me know if that does not work.

**Comment by anthonyg-1** [comment]
Ah I see what happened. I incorrectly parsed the incoming query. Fixing that now. The version you'll want that should address this is 1.0.3. Please let me know if that does not work.

**Comment by soke1556** [comment]
Nop, still same error with 1.0.3 installed.

![image](https://user-images.githubusercontent.com/1424405/113313684-de4fca00-92e1-11eb-8920-c50c9ba3cd56.png)

**Comment by anthonyg-1** [comment]
Can you ensure that 1.0.2 is completely gone and close and open your shell? That query passes for me in version 1.0.3. Please try that and let me know if that doesn't clear it up.

**Comment by anthonyg-1** [comment]
I think I know why you're getting that exception now. Please delete all prior versions, close PowerShell and install version 1.0.4 via the following: Install-Module PSGraphQL -Repository PSGallery -Scope CurrentUser -RequiredVersion 1.0.4

Please let me know the results after you do that.

**Comment by soke1556** [comment]
It finally worked after closing VSCode and opened it again as admin. It ran the query and got the results. Thanks a lot!

**Comment by anthonyg-1** [comment]
You're very welcome! Are you at version 1.0.4 currently? And please let me know if you have any suggestions for Invoke-GraphQLQuery.
