### ISSUE TITLE
Content for mutation losts CR and LF characters

### ISSUE THREAD

**Issue by soke1556** [anthonyg-1/PSGraphQL#3]
Hi @anthonyg-1 it happens that my content hits the server without CR and LF characters. I believe PSGraphQL is trimming them. Can you confirm please? Thanks!

**Comment by soke1556** [comment]
Solved on my side, by replacing cr by \n.

**Comment by anthonyg-1** [comment]
Good to know. Please let me know if you encounter any new issues. Are you using version 1.0.7? Could you use that and give me your feedback. Appreciate it!
