### ISSUE TITLE
Query with value continaing double spaces results in empty result

### ISSUE THREAD

**Issue by HarryPieterse** [anthonyg-1/PSGraphQL#8]
The command 
$cleanedQueryInput = Compress-String -InputString $Query 
in Invoke-GraphQLQuery.ps1 filters out the double spaces that I pass in variables.
This cleanup should be very carefull with this in the passed query.

**Comment by anthonyg-1** [comment]
Can you should me a sample query? It should only remove carriage returns
and trailing spaces.

**Comment by HarryPieterse** [comment]
Hi Tony,

An example is:
query productMeters { productMeters ( where:
  { name: { contains : "IS1020-20 - mBlock | Protect | X64 | Cloud OS | " } } )
  { name automated id }
}
    query productMeters1 {
        productMeters (
            where: {
                name: {
                  equals : "IS1020-20 - mBlock | Protect | X64 | Cloud OS |  1GB (1:4) | Run-time"
                }
            }
        )
        {
            name
            automated
            id
        }
    }


The  return ($InputString -replace '\s+', ' ').Trim()
In the Compress-String.ps1 replaces all subsequent spaces

Kind regards

Harry Pieterse

**Comment by anthonyg-1** [comment]
I'm definitely not understanding the issue. I just tested Compress-String against your query in isolation on Windows PowerShell 5.1 and PowerShell 7.2.2 on Windows and Linux and all I see is the removal of carriage returns as well as removing the trailing spaces. This is the result:

query productMeters { productMeters ( where: { name: { contains : "IS1020-20 - mBlock | Protect | X64 | Cloud OS | " } } ) { name automated id } } query productMeters1 { productMeters ( where: { name: { equals : "IS1020-20 - mBlock | Protect | X64 | Cloud OS | 1GB (1:4) | Run-time" } } ) { name automated id } }

I don't see any spaces being removed on Windows or Linux. What are you seeing and what are you seeing when this query is sent to your GraphQL server?

**Comment by anthonyg-1** [comment]
Now I see what's going on. It's replacing doublespaces with singles. To that end, what's the end result when the query is sent to your GraphQL server? What's the need for doublespaces in your query?

**Comment by HarryPieterse** [comment]
Hi Anthony,

The name of the productMeter is a manually provided one which needs to be able to contain multiple spaces.

Harry

**Comment by anthonyg-1** [comment]
I updated Compress-String to only remove new lines in version 1.5.5. Please get the latest version and let me know if this fixes the issue.

**Comment by anthonyg-1** [comment]
I believe the changes made should solve your issue. Please open a new one if that's not the case.

**Comment by anthonyg-1** [comment]
I believe the changes made should solve your issue. Please open a new one if that's not the case.
